---
title: Ervaren Scratch Sushi Cards
hero_image: images/banner.png
description: Maak een gave patroongenerator
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: De Pen gebruiken
  - 
    title: Patronen tekenen
  - 
    title: Input vragen
  - 
    title: Gavere lijnen
  - 
    title: Alles willekeurig maken
  - 
    title: De computer helpen
