title: Intermediate Scratch Sushi Cards
hero_image: images/banner.png
description: Make a cool pattern generator
theme: orange # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware: 
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Using the Pen tool
- title: Drawing patterns
- title: Asking for input
- title: Cooler lines
- title: Randomise the whole thing
- title: Helping the computer
