title: Intermediate Scratch Sushi Cards
hero_image: images/banner.png
description: Make a cool pattern generator
theme: orange # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware: 
software: scratch
version: 1
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Using the Pen tool
- title: Drawing patterns
- title: Asking for input
- title: Cooler lines
- title: Randomise the whole thing
- title: Helping the computer
