---
title: पैटर्न कलम
hero_image: images/banner.png
description: एक मजेदार​ पैटर्न जनरेटर बनाओ
theme: नारंगी #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art and design
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch (स्क्रैच)
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: पेन टूल का उपयोग करना
  - 
    title: ड्राइंग पैटर्न
  - 
    title: इनपुट के लिए पूछ रहा है
  - 
    title: मजे की लाइनें
  - 
    title: पूरी बात बेतरतीब ढंग से
  - 
    title: कंप्यूटर की मदद करना
