---
title: Lápiz de patrones
hero_image: images/banner.png
description: Haz un generador de patrones genial
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Cómo utilizar la herramienta Lápiz
  - 
    title: Patrones de dibujo
    completion:
      - engaged
  - 
    title: Pidiendo valores de entrada
  - 
    title: Líneas geniales
  - 
    title: Aleatorizar todo
  - 
    title: Ayudando al ordenador
    completion:
      - internal
