---
title: Stiloul cu șabloane
hero_image: images/banner.png
description: Construiește un generator de șabloane interesante
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: artă
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
- title: Introducere
  completion: engaged
- title: Utilizarea instrumentului Stilou
- title: Șabloane de desen
- title: Obținerea datelor de intrare
- title: Linii mai interesante
- title: Fă totul aleatoriu
  completion: internal
- title: Ajută computer-ul
