---
title: Caneta de padrões
hero_image: images/banner.png
description: Faça um gerador de padrões legal
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Usando a ferramenta Caneta
  - 
    title: Desenhando padrões
    completion:
      - engaged
  - 
    title: Pedindo valores de entrada
  - 
    title: Linhas mais legais
  - 
    title: Torne tudo aleatório
  - 
    title: Ajudando o computador
    completion:
      - internal
