---
title: ನಮೂನೆಯ ಪೆನ್
hero_image: images/banner.png
description: ಚೆನ್ನಾಗಿರುವ ನಮೂನೆ ಉತ್ಪದಕವನ್ನು ಮಾಡಿ
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
- title: ಪರಿಚಯ
  completion: engaged
- title: ಪೆನ್ ಉಪಕರಣವನ್ನು ಬಳಸುವುದು
- title: ಡ್ರಾಯಿಂಗ್ ಪ್ಯಾಟರ್ನ್ಸ್
- title: ಇನ್ಪುಟ್ ಕೇಳುತ್ತಿದೆ
- title: ಚೆನ್ನಾಗಿರುವ ರೇಖೆಗಳು
- title: ಇಡೀ ವಿಷಯವನ್ನು ಯಾದೃಚಿಕಗೊಳಿಸಿ
  completion: internal
- title: ಕಂಪ್ಯೂಟರ್ಗೆ ಸಹಾಯ ಮಾಡಲಾಗುತ್ತಿದೆ
