---
title: Patrón de Lápiz
hero_image: images/banner.png
description: Crea un generador de patrones genial
theme: orange #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: arte
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Utilizando la herramienta Lápiz
  - 
    title: Patrones de dibujo
  - 
    title: Pedir variables
  - 
    title: Líneas más atractivas
  - 
    title: Todo en aleatorio
  - 
    title: Ayudando a la computadora
