---
title: Wzór pióra
hero_image: images/banner.png
description: Stwórz generator fajnych wzorów
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Korzystanie z narzędzia Pióro
  - 
    title: Rysowanie wzorów
    completion:
      - engaged
  - 
    title: Pytanie o dane wejściowe
  - 
    title: Ciekawsze linie
  - 
    title: Ustaw wszystko losowo
  - 
    title: Pomaganie komputerowi
    completion:
      - internal
