---
title: Penna modello
hero_image: images/banner.png
description: Crea un fantastico generatore di modelli
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: scratch
site_areas: coderdojo
hardware:
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
- title: Introduzione
  completion: engaged
- title: Usare lo strumento Penna
- title: Disegno dei modelli
- title: Richiesta di immissione
- title: Linee più accattivanti
- title: Rimescolare il tutto
  completion: internal
- title: Aiutare il computer
